# composite tasks
[tasks.upgrade]
dependencies = ["upgrade-deps", "update"]

[tasks.check]
dependencies = ["fmt", "clippy", "test"]

# cleaning
[tasks.clean-state]
script = """
rm ferox-*.state
"""

# dependency management
[tasks.upgrade-deps]
command = "cargo"
args = ["upgrade", "--exclude", "self_update"]

[tasks.update]
command = "cargo"
args = ["update"]

# clippy / lint
[tasks.clippy]
clear = true
script = """
cargo clippy --all-targets --all-features -- -D warnings
"""

[tasks.fmt]
clear = true
script = """
cargo fmt --all
"""

# tests
[tasks.test]
clear = true
script = """
cargo nextest run --all-features --all-targets --retries 4 --no-fail-fast
"""
